### PR TITLE
Project.getKotlinPluginVersion also in spek to work with kotlin > 1.7.x

### LINKED ISSUE #211: ch.tutteli.gradle.plugins.spek does not support Kotlin 1.7+
Here's a stacktrace:

```
        groovy.lang.MissingMethodException: No signature of method:
org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper.getKotlinPluginVersion() is applicable for argument types: () values: []
            at ch.tutteli.gradle.plugins.spek.SpekPlugin.getKotlinVersion(SpekPlugin.groovy:77)
            at ch.tutteli.gradle.plugins.spek.SpekPlugin.configureForJvm(SpekPlugin.groovy:44)
            at ch.tutteli.gradle.plugins.spek.SpekPlugin$_apply_closure2.doCall(SpekPlugin.groovy:37)
```

### PR DESCRIPTION
**Pull request by robstoll**
fixes #211

### CODE REVIEW

File: tutteli-gradle-spek/src/main/groovy/ch/tutteli/gradle/plugins/spek/SpekPlugin.groovy [hunk 1]
```diff
@@ -65,12 +66,32 @@ class SpekPlugin implements Plugin<Project> {
...
-        def kotlinPlugin = plugins.findPlugin('kotlin')
-            ?: plugins.findPlugin('kotlin-platform-jvm')
-            ?: plugins.findPlugin('org.jetbrains.kotlin.multiplatform')
-            ?: plugins.findPlugin('org.jetbrains.kotlin.jvm')
-        def version = kotlinPlugin?.getKotlinPluginVersion()
+        def version
+        try {
+            version = KotlinPluginWrapperKt.getKotlinPluginVersion(project)
+        } catch (MissingMethodException e) {
+            e.printStackTrace()
```
Comment (vlsi) [inline tutteli-gradle-spek/src/main/groovy/ch/tutteli/gradle/plugins/spek/SpekPlugin.groovy:73]: Please do not use `printStackTrace` as it will pollute the console output.

File: tutteli-gradle-spek/src/main/groovy/ch/tutteli/gradle/plugins/spek/SpekPlugin.groovy [hunk 2]
```diff
@@ -65,12 +66,32 @@ class SpekPlugin implements Plugin<Project> {
...
+                // TODO drop once we no longer support the old kotlin plugins and old gradle version
+                plugins.findPlugin("kotlin")
+                    ?: plugins.findPlugin("kotlin2js")
+                    ?: plugins.findPlugin("kotlin-platform-jvm")
+                    ?: plugins.findPlugin("kotlin-platform-js")
+                    ?: plugins.findPlugin("kotlin-common")
+                    ?: plugins.findPlugin("org.jetbrains.kotlin.multiplatform")
+                    ?: plugins.findPlugin("org.jetbrains.kotlin.jvm")
+                    ?: plugins.findPlugin("org.jetbrains.kotlin.js")
+            version = kotlinPlugin?.getKotlinPluginVersion()
```
Comment (vlsi) [inline tutteli-gradle-spek/src/main/groovy/ch/tutteli/gradle/plugins/spek/SpekPlugin.groovy:92]: `findPlugin` enforces a ceratin plugin application order, so it is a bad practice.
If you really want to react to plugins for some reason, consider using `plugins.withId(pluginId)` instead:

```kotlin
plugins.withId("kotlin") {
    // executed if the project applies kotlin plugin
}
plugins.withId("kotlin2js") {
    // executed if the project applies kotlin2js plugin
}
```

File: tutteli-gradle-spek/src/main/groovy/ch/tutteli/gradle/plugins/spek/SpekPlugin.groovy (hunk 1 above)
Comment (robstoll) [reply tutteli-gradle-spek/src/main/groovy/ch/tutteli/gradle/plugins/spek/SpekPlugin.groovy:73]: thanks, that was only a test and should have been removed

File: tutteli-gradle-spek/src/main/groovy/ch/tutteli/gradle/plugins/spek/SpekPlugin.groovy (hunk 2 above)
Comment (robstoll) [reply tutteli-gradle-spek/src/main/groovy/ch/tutteli/gradle/plugins/spek/SpekPlugin.groovy:92]: thanks for the hint

File: tutteli-gradle-publish/src/main/kotlin/ch.tutteli.gradle.plugins.publish/PublishPlugin.kt [hunk 3]
```diff
@@ -259,14 +259,14 @@ class PublishPlugin : Plugin<Project> {
...
-                    ?: it.findPlugin("org.jetbrains.kotlin.jvm")
-                    ?: it.findPlugin("org.jetbrains.kotlin.js")
+                it.withId("kotlin")
+                    ?: it.withId("kotlin2js")
+                    ?: it.withId("kotlin-platform-jvm")
+                    ?: it.withId("kotlin-platform-js")
+                    ?: it.withId("kotlin-common")
+                    ?: it.withId("org.jetbrains.kotlin.multiplatform")
+                    ?: it.withId("org.jetbrains.kotlin.jvm")
+                    ?: it.withId("org.jetbrains.kotlin.js")
```
[the remark this answers is not in the document]
Comment (robstoll) [reply tutteli-gradle-publish/src/main/kotlin/ch.tutteli.gradle.plugins.publish/PublishPlugin.kt:269]: no it doesn't. intellij and gradle crashed locally and I thought let's just mis-use github to tell me if it works.
